### PR TITLE
sdk/tests: check all packages are up to date

### PR DESCRIPTION
**Pull request by xnox**
Check that everything is up to date

Freshly minted image, should be fully up to date, this however will catch any package renames/provides that apko resolved using out of date packages, due to packaging mistakes or ongoing transitions

Non-fatal for now

Related: https://github.com/wolfi-dev/os/pull/14692

CC @smoser

### CODE REVIEW

**Review by smoser — COMMENTED** [review]
Will this test ever fail?  The only way I see for it to fail is if bash isn't present in the image.

Its not clear to me what this will accomplish.  Can you give an example of a failure that it would catch?

**Comment by xnox** [comment]
> Will this test ever fail? The only way I see for it to fail is if bash isn't present in the image.
> 
> Its not clear to me what this will accomplish. Can you give an example of a failure that it would catch?

At first I am adding it as `|| true` to ensure it usually passes fine as visible in the logs.

If it passes without printing errors on a few runs, will submit a pr to drop the `|| true` to make it enforcing.

The point is to catch package reorgs, which end up resolving and building images with out of date packages, like we had with libxcrypt transition.

**Comment by xnox** [comment]
@smoser ideally i want this check to be merged, before doing part ii merge of https://github.com/wolfi-dev/os/pull/15069

**Review by smoser — APPROVED** [review]
This looks good for now. we just have to remember to drop it.

**Review by jonjohnsonjr — APPROVED** [review]

**Review by imjasonh — APPROVED** [review]

**Review by mamccorm — APPROVED** [review]

**Pull request merged**
